<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BackAuto</AssemblyName>
    <RootNamespace>BackAuto</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU</Platforms>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="logo.ico" />
  </ItemGroup>
</Project>
